app:
  image:
    repository: kauapereira/file-processor
    tag: "1.0.0"
    pullPolicy: Always

  env:
    DEPLOYMENT_ENVIRONMENT_NAME: prod
    SPRING_PROFILES_ACTIVE: prod
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: otlp
    OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.app.svc.cluster.local:4317
    OTEL_EXPORTER_OTLP_METRICS_PROTOCOL: http/protobuf
    OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector.app.svc.cluster.local:4318/v1/metrics
    OTEL_INSTRUMENTATION_SERVLET_EXCLUDE_PATTERN: /actuator/.*|/health|/metrics
    OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_LOG_ATTRIBUTES: "true"
    OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_CODE_ATTRIBUTES: "true"
    OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MARKER_ATTRIBUTE: "true"
    OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_KEY_VALUE_PAIR_ATTRIBUTES: "true"
    OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MDC_ATTRIBUTES: "*"

  externalSecret:
    dataFromKey: dev/file-processor
#    dataFromKey: prod/file-processor

  kafka:
    securityProtocol: SASL_SSL
    saslMechanism: AWS_MSK_IAM

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::518216637660:role/file-processor-es-sa
#      eks.amazonaws.com/role-arn: arn:aws:iam::518216637660:role/file-processor-irsa

  secretStore:
    region: us-east-1
#    auth:
#      type: jwt

  ingress:
    enabled: true
    className: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
#    host: api.mydomain.com