apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      serviceAccountName: {{ .Values.app.serviceAccount.name }}
      terminationGracePeriodSeconds: 40
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: {{ .Values.app.securityContext.type }}

      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.ports.containerPort }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          envFrom:
            - secretRef:
                name: {{ .Values.app.externalSecret.secretName }}

          env:
            # ===== OPENTELEMETRY =====
            - name: OTEL_TRACES_EXPORTER
              value: {{ .Values.app.env.OTEL_TRACES_EXPORTER | quote }}
            - name: OTEL_METRICS_EXPORTER
              value: {{ .Values.app.env.OTEL_METRICS_EXPORTER | quote }}
            - name: OTEL_LOGS_EXPORTER
              value: {{ .Values.app.env.OTEL_LOGS_EXPORTER | quote }}
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: {{ .Values.app.env.OTEL_EXPORTER_OTLP_PROTOCOL | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.app.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
            - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
              value: {{ .Values.app.env.OTEL_EXPORTER_OTLP_METRICS_PROTOCOL | quote }}
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: {{ .Values.app.env.OTEL_EXPORTER_OTLP_METRICS_ENDPOINT | quote }}
            - name: OTEL_INSTRUMENTATION_SERVLET_EXCLUDE_PATTERN
              value: {{ .Values.app.env.OTEL_INSTRUMENTATION_SERVLET_EXCLUDE_PATTERN | quote }}
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_LOG_ATTRIBUTES
              value: {{ .Values.app.env.OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_LOG_ATTRIBUTES | quote }}
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_CODE_ATTRIBUTES
              value: {{ .Values.app.env.OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_CODE_ATTRIBUTES | quote }}
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MARKER_ATTRIBUTE
              value: {{ .Values.app.env.OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MARKER_ATTRIBUTE | quote }}
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_KEY_VALUE_PAIR_ATTRIBUTES
              value: {{ .Values.app.env.OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_KEY_VALUE_PAIR_ATTRIBUTES | quote }}
            - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MDC_ATTRIBUTES
              value: {{ .Values.app.env.OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_CAPTURE_MDC_ATTRIBUTES | quote }}
            - name: DEPLOYMENT_ENVIRONMENT_NAME
              value: {{ .Values.app.env.DEPLOYMENT_ENVIRONMENT_NAME | quote }}

            # ===== SPRING =====
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.app.env.SPRING_PROFILES_ACTIVE | quote }}

            # ===== KAFKA (MSK IAM) =====
            - name: KAFKA_SECURITY_PROTOCOL
              value: {{ .Values.app.kafka.securityProtocol | quote }}

            - name: KAFKA_SASL_MECHANISM
              value: {{ .Values.app.kafka.saslMechanism | quote }}

            # ===== DATABASE =====
            - name: DB_PORT
              value: {{ .Values.app.database.port | quote }}

            - name: DB_NAME
              value: {{ .Values.app.database.name | quote }}

            # DB_PASSWORD get in Secret Manager

            # ===== REDIS =====
            - name: REDIS_PORT
              value: {{ .Values.app.redis.port | quote }}

          resources:
  {{- toYaml .Values.app.resources | nindent 12 }}


          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.app.ports.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.app.ports.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 10