apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      serviceAccountName: {{ .Values.app.serviceAccount.name }}
      terminationGracePeriodSeconds: 40
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: {{ .Values.app.securityContext.type }}

      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          envFrom:
            - secretRef:
                name: {{ .Values.app.externalSecret.secretName }}

          env:
            - name: DEPLOYMENT_ENVIRONMENT_NAME
              value: {{ .Values.app.env.DEPLOYMENT_ENVIRONMENT_NAME | quote }}

            # ===== SPRING =====
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.app.env.SPRING_PROFILES_ACTIVE | quote }}

            # ===== KAFKA (MSK IAM) =====
            - name: KAFKA_SECURITY_PROTOCOL
              value: {{ .Values.app.kafka.securityProtocol | quote }}

            - name: KAFKA_SASL_MECHANISM
              value: {{ .Values.app.kafka.saslMechanism | quote }}

            # ===== DATABASE =====
            - name: DB_PORT
              value: {{ .Values.app.database.port | quote }}

            - name: DB_NAME
              value: {{ .Values.app.database.name | quote }}

            # DB_PASSWORD get in Secret Manager

            # ===== REDIS =====
            - name: REDIS_PORT
              value: {{ .Values.app.redis.port | quote }}

          resources:
  {{- toYaml .Values.app.resources | nindent 12 }}


          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.app.ports.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.app.ports.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 10