{{- if .Values.app.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.externalSecret.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  refreshInterval: {{ .Values.app.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.app.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.app.externalSecret.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.app.externalSecret.dataFromKey }}
  {{- end }}
