apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.app.secretStore.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.app.secretStore.region }}
#      {{- if eq .Values.app.secretStore.auth.type "jwt" }}
#      auth:
#        jwt:
#          serviceAccountRef:
#            name: {{ .Values.app.serviceAccount.name }}
#      {{- else }}
#      endpoint: {{ .Values.app.secretStore.endpoint }}
#      auth:
#        secretRef:
#          accessKeyIDSecretRef:
#            name: {{ .Values.app.secretStore.auth.secretRefName }}
#            key: access-key
#          secretAccessKeySecretRef:
#            name: {{ .Values.app.secretStore.auth.secretRefName }}
#            key: secret-key
#      {{- end }}
