apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.serviceAccount.name }}
  namespace: {{ .Values.app.namespace }}
   {{- if .Values.app.serviceAccount.annotations }}
  annotations:
   {{ toYaml .Values.app.serviceAccount.annotations | indent 4 }}
   {{- end }}
